In [142]:
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np 
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

## In this notebook I did some feature engineering to cut down on our columns

In [143]:
train = pd.read_csv('../Resources/train_allvalues.csv')
test=pd.read_csv('../Resources/test.csv')

In [82]:
train_copy = train.copy()
train_copy.shape

(1412, 78)

In [83]:
#dropped columns first dropped columns that we decided were unneeded or redundant. Then went ahead and found columns 
# with high single value counts and dropped them. 

def feature_selector(df, train=train):
    df.drop(columns=['Id','MiscVal','PoolArea','Utilities','YearRemodAdd','GarageYrBlt'], inplace=True)
    num_values = len(train)
    for x in df.columns: 
        num_unique = df[x].nunique()


        if (num_unique <30):
            v_count= df[x].value_counts()
            single_value = round(v_count.iloc[0] / num_values,2)


            if (single_value > .60) :
                print(f"dropping column : {x}")
                df.drop(columns=x,inplace=True)
                
    return df

In [84]:
f_train = feature_selector(train_copy)

dropping column : MSZoning
dropping column : Street
dropping column : LotShape
dropping column : LandContour
dropping column : LotConfig
dropping column : LandSlope
dropping column : Condition1
dropping column : Condition2
dropping column : BldgType
dropping column : RoofStyle
dropping column : RoofMatl
dropping column : ExterQual
dropping column : ExterCond
dropping column : BsmtCond
dropping column : BsmtExposure
dropping column : BsmtFinType2
dropping column : Heating
dropping column : CentralAir
dropping column : Electrical
dropping column : LowQualFinSF
dropping column : BsmtHalfBath
dropping column : HalfBath
dropping column : KitchenAbvGr
dropping column : Functional
dropping column : GarageQual
dropping column : GarageCond
dropping column : PavedDrive
dropping column : 3SsnPorch
dropping column : Fence
dropping column : SaleType
dropping column : SaleCondition

In [73]:
f_train.shape

(1412, 41)

In [85]:
#combined all porch and deck SQ.Footage and created a column called OutdoorAreaSF. 
#dropped basement and 1st floor and 2nd floor Sq.Footage columns - I did this because these numbers are combined in other 
#pre-existing columns 
def Bsmt_porch (df):
    df = df.drop(columns=['BsmtFinSF2','BsmtFinSF1','BsmtUnfSF','2ndFlrSF','1stFlrSF'])
    df['outdoorAreaSF'] = df['OpenPorchSF']+df['EnclosedPorch']+df['ScreenPorch']+df['WoodDeckSF']
    df['outdoorAreaSF']
    df = df.drop(columns = ['OpenPorchSF','EnclosedPorch','ScreenPorch','WoodDeckSF'])
    

    return(df)

In [86]:
f_train = Bsmt_porch(f_train)
f_train

,MSSubClass,LotFrontage,LotArea,Neighborhood,HouseStyle,OverallQual,OverallCond,YearBuilt,Exterior1st,Exterior2nd,...,Fireplaces,FireplaceQu,GarageType,GarageFinish,GarageCars,GarageArea,MoSold,YrSold,SalePrice,outdoorAreaSF
0,60,65.0,8450,CollgCr,2Story,7,5,2003,VinylSd,VinylSd,...,0,none,Attchd,RFn,2,548,2,2008,208500,61
1,20,80.0,9600,Veenker,1Story,6,8,1976,MetalSd,MetalSd,...,1,TA,Attchd,RFn,2,460,5,2007,181500,298
2,60,68.0,11250,CollgCr,2Story,7,5,2001,VinylSd,VinylSd,...,1,TA,Attchd,RFn,2,608,9,2008,223500,42
3,70,60.0,9550,Crawfor,2Story,7,5,1915,Wd Sdng,Wd Shng,...,1,Gd,Detchd,Unf,3,642,2,2006,140000,307
4,60,84.0,14260,NoRidge,2Story,8,5,2000,VinylSd,VinylSd,...,1,TA,Attchd,RFn,3,836,12,2008,250000,276
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1407,60,62.0,7917,Gilbert,2Story,6,5,1999,VinylSd,VinylSd,...,1,TA,Attchd,RFn,2,460,8,2007,175000,40
1408,20,85.0,13175,NWAmes,1Story,6,6,1978,Plywood,Plywood,...,2,TA,Attchd,Unf,2,500,2,2010,210000,349
1409,70,66.0,9042,Crawfor,2Story,7,9,1941,CemntBd,CmentBd,...,2,Gd,Attchd,RFn,1,252,5,2010,266500,60
1410,20,68.0,9717,NAmes,1Story,5,6,1950,MetalSd,MetalSd,...,0,none,Attchd,Unf,1,240,4,2010,142125,478
1411,20,75.0,9937,Edwards,1Story,5,6,1965,HdBoard,HdBoard,...,0,none,Attchd,Fin,1,276,6,2008,147500,804

In [66]:
f_train

,MSSubClass,LotFrontage,LotArea,Neighborhood,HouseStyle,OverallQual,OverallCond,YearBuilt,Exterior1st,Exterior2nd,...,Fireplaces,FireplaceQu,GarageType,GarageFinish,GarageCars,GarageArea,MoSold,YrSold,SalePrice,outdoorAreaSF
0,60,65.0,8450,CollgCr,2Story,7,5,2003,VinylSd,VinylSd,...,0,none,Attchd,RFn,2,548,2,2008,208500,61
1,20,80.0,9600,Veenker,1Story,6,8,1976,MetalSd,MetalSd,...,1,TA,Attchd,RFn,2,460,5,2007,181500,298
2,60,68.0,11250,CollgCr,2Story,7,5,2001,VinylSd,VinylSd,...,1,TA,Attchd,RFn,2,608,9,2008,223500,42
3,70,60.0,9550,Crawfor,2Story,7,5,1915,Wd Sdng,Wd Shng,...,1,Gd,Detchd,Unf,3,642,2,2006,140000,307
4,60,84.0,14260,NoRidge,2Story,8,5,2000,VinylSd,VinylSd,...,1,TA,Attchd,RFn,3,836,12,2008,250000,276
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1407,60,62.0,7917,Gilbert,2Story,6,5,1999,VinylSd,VinylSd,...,1,TA,Attchd,RFn,2,460,8,2007,175000,40
1408,20,85.0,13175,NWAmes,1Story,6,6,1978,Plywood,Plywood,...,2,TA,Attchd,Unf,2,500,2,2010,210000,349
1409,70,66.0,9042,Crawfor,2Story,7,9,1941,CemntBd,CmentBd,...,2,Gd,Attchd,RFn,1,252,5,2010,266500,60
1410,20,68.0,9717,NAmes,1Story,5,6,1950,MetalSd,MetalSd,...,0,none,Attchd,Unf,1,240,4,2010,142125,478
1411,20,75.0,9937,Edwards,1Story,5,6,1965,HdBoard,HdBoard,...,0,none,Attchd,Fin,1,276,6,2008,147500,804

In [161]:
#Exported the new CSV, So team members could look at which columns I am using to model 
f_train.to_csv("../Resources/thirtythree.csv", index=False)

### The rest of the notebook is me working on creating a preprocessing pipeline.  Look @ the notebook titled pipeline_models_33columns to see the finished work.

In [139]:
f_train.MSSubClass = f_train.MSSubClass.astype("int")

In [140]:
f_train.dtypes

MSSubClass         int32
LotFrontage      float64
LotArea            int64
Neighborhood      object
HouseStyle        object
OverallQual        int64
OverallCond        int64
YearBuilt          int64
Exterior1st       object
Exterior2nd       object
MasVnrType        object
MasVnrArea       float64
Foundation        object
BsmtQual          object
BsmtFinType1      object
TotalBsmtSF        int64
HeatingQC         object
GrLivArea          int64
BsmtFullBath       int64
FullBath           int64
BedroomAbvGr       int64
KitchenQual       object
TotRmsAbvGrd       int64
Fireplaces         int64
FireplaceQu       object
GarageType        object
GarageFinish      object
GarageCars         int64
GarageArea         int64
MoSold             int64
YrSold             int64
SalePrice          int64
outdoorAreaSF      int64
dtype: object

In [141]:
encoder=OneHotEncoder()
col_hot = f_train['MSSubClass'].values.reshape(-1,1)
one_hot = encoder.fit(col_hot)
test = one_hot.transform(f_train.MSSubClass.values.reshape(-1,1))

In [142]:
test.shape

(1412, 15)

In [143]:
one_hot.get_feature_names()

array(['x0_20', 'x0_30', 'x0_40', 'x0_45', 'x0_50', 'x0_60', 'x0_70',
       'x0_75', 'x0_80', 'x0_85', 'x0_90', 'x0_120', 'x0_160', 'x0_180',
       'x0_190'], dtype=object)

In [144]:
df_test = pd.DataFrame.sparse.from_spmatrix(test, columns=one_hot.get_feature_names())

In [146]:
df_test.head()

,x0_20,x0_30,x0_40,x0_45,x0_50,x0_60,x0_70,x0_75,x0_80,x0_85,x0_90,x0_120,x0_160,x0_180,x0_190
0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [119]:
one_hot.todense()

matrix([[0., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.]])

In [31]:
label_encode = f_train.select_dtypes(exclude=['number']).columns.tolist()
label_encode

['Neighborhood',
 'HouseStyle',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'Foundation',
 'BsmtQual',
 'BsmtFinType1',
 'HeatingQC',
 'KitchenQual',
 'FireplaceQu',
 'GarageType',
 'GarageFinish']

In [67]:
label_encode = f_train.select_dtypes(exclude=['number']).columns.tolist()
numeric_classes = ['MSSubClass', 'OverallQual','OverallCond']
onehot = numeric_classes+label_encode
for x in onehot: 
    one_hot = pd.get_dummies(f_train[x])
    f_train.drop(columns=[x], inplace=True)
    one_hot = one_hot.add_prefix(x + '_')
    f_train=f_train.join(one_hot)
    
f_train

,LotFrontage,LotArea,YearBuilt,MasVnrArea,TotalBsmtSF,GrLivArea,BsmtFullBath,FullBath,BedroomAbvGr,TotRmsAbvGrd,...,GarageType_Attchd,GarageType_Basment,GarageType_BuiltIn,GarageType_CarPort,GarageType_Detchd,GarageType_none,GarageFinish_Fin,GarageFinish_RFn,GarageFinish_Unf,GarageFinish_none
0,65.0,8450,2003,196.0,856,1710,1,2,3,8,...,1,0,0,0,0,0,0,1,0,0
1,80.0,9600,1976,0.0,1262,1262,0,2,3,6,...,1,0,0,0,0,0,0,1,0,0
2,68.0,11250,2001,162.0,920,1786,1,2,3,6,...,1,0,0,0,0,0,0,1,0,0
3,60.0,9550,1915,0.0,756,1717,1,1,3,7,...,0,0,0,0,1,0,0,0,1,0
4,84.0,14260,2000,350.0,1145,2198,1,2,4,9,...,1,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1407,62.0,7917,1999,0.0,953,1647,0,2,3,7,...,1,0,0,0,0,0,0,1,0,0
1408,85.0,13175,1978,119.0,1542,2073,1,2,3,7,...,1,0,0,0,0,0,0,0,1,0
1409,66.0,9042,1941,0.0,1152,2340,0,2,4,9,...,1,0,0,0,0,0,0,1,0,0
1410,68.0,9717,1950,0.0,1078,1078,1,1,2,5,...,1,0,0,0,0,0,0,0,1,0
1411,75.0,9937,1965,0.0,1256,1256,1,1,3,6,...,1,0,0,0,0,0,1,0,0,0

In [137]:
def label (df):
    le=LabelEncoder()
    encoder=OneHotEncoder()
    label_encode = df.select_dtypes(exclude=['number']).columns.tolist()
    

    for x in label_encode:
        col = df[x]
        label = le.fit_transform(col)
        df[x]=label
        
       

        
        
       
    return df

In [138]:
label(f_train)

,MSSubClass,LotFrontage,LotArea,Neighborhood,HouseStyle,OverallQual,OverallCond,YearBuilt,Exterior1st,Exterior2nd,...,Fireplaces,FireplaceQu,GarageType,GarageFinish,GarageCars,GarageArea,MoSold,YrSold,SalePrice,outdoorAreaSF
0,60,65.0,8450,5,5,7,5,2003,11,13,...,0,5,1,1,2,548,2,2008,208500,61
1,20,80.0,9600,24,2,6,8,1976,7,8,...,1,4,1,1,2,460,5,2007,181500,298
2,60,68.0,11250,5,5,7,5,2001,11,13,...,1,4,1,1,2,608,9,2008,223500,42
3,70,60.0,9550,6,5,7,5,1915,12,15,...,1,2,5,2,3,642,2,2006,140000,307
4,60,84.0,14260,15,5,8,5,2000,11,13,...,1,4,1,1,3,836,12,2008,250000,276
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1407,60,62.0,7917,8,5,6,5,1999,11,13,...,1,4,1,1,2,460,8,2007,175000,40
1408,20,85.0,13175,14,2,6,6,1978,8,10,...,2,4,1,2,2,500,2,2010,210000,349
1409,70,66.0,9042,6,5,7,9,1941,4,5,...,2,2,1,1,1,252,5,2010,266500,60
1410,20,68.0,9717,12,2,5,6,1950,7,8,...,0,5,1,2,1,240,4,2010,142125,478
1411,20,75.0,9937,7,2,5,6,1965,5,6,...,0,5,1,0,1,276,6,2008,147500,804

In [121]:
onehot(f_train)

,MSSubClass,LotFrontage,LotArea,Neighborhood,HouseStyle,OverallQual,OverallCond,YearBuilt,Exterior1st,Exterior2nd,...,Fireplaces,FireplaceQu,GarageType,GarageFinish,GarageCars,GarageArea,MoSold,YrSold,SalePrice,outdoorAreaSF
0,60,65.0,8450,5,5,7,5,2003,11,13,...,0,5,1,1,2,548,2,2008,208500,61
1,20,80.0,9600,24,2,6,8,1976,7,8,...,1,4,1,1,2,460,5,2007,181500,298
2,60,68.0,11250,5,5,7,5,2001,11,13,...,1,4,1,1,2,608,9,2008,223500,42
3,70,60.0,9550,6,5,7,5,1915,12,15,...,1,2,5,2,3,642,2,2006,140000,307
4,60,84.0,14260,15,5,8,5,2000,11,13,...,1,4,1,1,3,836,12,2008,250000,276
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1407,60,62.0,7917,8,5,6,5,1999,11,13,...,1,4,1,1,2,460,8,2007,175000,40
1408,20,85.0,13175,14,2,6,6,1978,8,10,...,2,4,1,2,2,500,2,2010,210000,349
1409,70,66.0,9042,6,5,7,9,1941,4,5,...,2,2,1,1,1,252,5,2010,266500,60
1410,20,68.0,9717,12,2,5,6,1950,7,8,...,0,5,1,2,1,240,4,2010,142125,478
1411,20,75.0,9937,7,2,5,6,1965,5,6,...,0,5,1,0,1,276,6,2008,147500,804

In [125]:
def onehot(df):
    label_encode = df.select_dtypes(exclude=['number']).columns.tolist()
    numeric_classes = ['MSSubClass', 'OverallQual','OverallCond']
    onehot = numeric_classes+label_encode
    for x in onehot: 
        
        df[x]=df[x].astype('object')
        one_hot = pd.get_dummies(df[x])
        df.drop(columns=[x], inplace=True)
        one_hot = one_hot.add_prefix(x + '_')
        df=df.join(one_hot)
    return df

In [141]:
label_encode = f_train.select_dtypes(exclude=['number']).columns.tolist()
numeric_classes = ['MSSubClass', 'OverallQual','OverallCond']
onehot = numeric_classes+label_encode
onehot

['MSSubClass',
 'OverallQual',
 'OverallCond',
 'Neighborhood',
 'HouseStyle',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'Foundation',
 'BsmtQual',
 'BsmtFinType1',
 'HeatingQC',
 'KitchenQual',
 'FireplaceQu',
 'GarageType',
 'GarageFinish']

In [134]:
f_train.select_dtypes(exclude=['number']).columns.tolist()

['Neighborhood',
 'HouseStyle',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'Foundation',
 'BsmtQual',
 'BsmtFinType1',
 'HeatingQC',
 'KitchenQual',
 'FireplaceQu',
 'GarageType',
 'GarageFinish']

In [98]:
numeric_classes = ['MSSubClass', 'OverallQual','OverallCond']

In [99]:
to_scale=f_train3.select_dtypes(include=['number']).drop(columns=numeric_classes)

In [101]:
scale_these = to_scale.columns

In [102]:
scale_these

Index(['LotFrontage', 'LotArea', 'YearBuilt', 'MasVnrArea', 'TotalBsmtSF',
       'GrLivArea', 'BsmtFullBath', 'FullBath', 'BedroomAbvGr', 'TotRmsAbvGrd',
       'Fireplaces', 'GarageCars', 'GarageArea', 'MoSold', 'YrSold',
       'SalePrice', 'outdoorAreaSF'],
      dtype='object')

In [105]:
label_encode = f_train3.select_dtypes(exclude=['number']).columns